---
- name: Install and start Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update Package
      apt:
        update_cache: yes

    - name: Install Nginx
      apt: 
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started